apiVersion: v1
kind: Service
metadata:
  name: ai-chat-web
  namespace: ai-rag
spec:
  selector:
    app: ai-chat-web
  ports:
    - name: http
      port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-chat-web
  namespace: ai-rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-chat-web
  template:
    metadata:
      labels:
        app: ai-chat-web
    spec:
      serviceAccountName: ai-rag-sa

      # Blindaje: evita variables auto-inyectadas por Services
      enableServiceLinks: false

      # Evita CrashLoop: espera a que Chroma estÃ© arriba antes de arrancar Gunicorn/Flask
      initContainers:
        - name: wait-for-chroma
          image: curlimages/curl:8.5.0
          command: ["sh", "-c"]
          args:
            - >
              echo "Waiting for Chroma...";
              until curl -sf http://chroma-svc:8000/api/v2/heartbeat >/dev/null; do
                sleep 2;
              done;
              echo "Chroma is up.";

      containers:
        - name: web
          image: 084375558336.dkr.ecr.us-east-1.amazonaws.com/chroma-chat-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: AWS_REGION
              value: us-east-1

            # Chroma (usar el service correcto)
            - name: CHROMA_HOST
              value: chroma-svc
            - name: CHROMA_PORT
              value: "8000"
            - name: CHROMA_COLLECTION
              value: info_ia_generativa

             
            # Flask session key (secreto local de app)
            - name: FLASK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: webapp-secrets
                  key: FLASK_SECRET_KEY

            # Kubecost
            - name: KUBECOST_BASE
              value: http://kubecost-cost-analyzer.kubecost:9090
            - name: KUBECOST_WINDOW
              value: "false"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"