apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-chat-web
  namespace: ai-rag
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: ai-chat.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-chat-web
                port:
                  number: 80
